stages:
   - build
   - deploy

build_releases:
  stage: build
  before_script: 
    - git submodule update --init
  script:
    - /bin/bash build-deb.sh
    - /usr/local/bin/deploy-package -C pvc
  only:
    - tags
  except:
    - branches
