stages:
   - build
   - deploy

build:
  stage: build
  before_script: 
    - git submodule update --init
  script:
    - /usr/local/bin/build-package 0.5
    - /usr/local/bin/deploy-package
  artifacts:
    paths:
      - "*.deb"
  only:
    - master
