stages:
   - build
   - deploy

build:
  stage: build
  before_script: 
    - git submodule update --init
  script:
    - /bin/bash build-deb.sh
    - /usr/local/bin/deploy-package
  only:
    - master
