#cloud-config
# Example user-data file to set up an alternate /var/home, a first user and some SSH keys, and some packages
bootcmd:
  - "mv /home /var/"
  - "locale-gen"
package_update: true
packages:
  - openssh-server
  - sudo
users:
  - name: deploy
    gecos: Deploy User
    homedir: /var/home/deploy
    sudo: "ALL=(ALL) NOPASSWD: ALL"
    groups: adm, sudo
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBRBGPzlbh5xYD6k8DMZdPNEwemZzKSSpWGOuU72ehfN joshua@bonifacelabs.net 2017-04
usercmd:
  - "groupmod -g 200 deploy"
  - "usermod -u 200 deploy"
  - "userdel debian"
  - "systemctl disable cloud-init.target"
